version: '3'

services:
  dyn-dns-checker:
    image: ubuntu:focal
    container_name: dyn-dns-checker
    environment:
      - TZ=America/Denver
    tty: true
    stdin_open: true
    #command: ["/entrypoint.sh"]
    deploy:
      resources:
          limits:
              cpus: '1.0'
              memory: 128M
    logging:
        options:
            max-size: 1g
    restart: unless-stopped
