version: '3'

services:
  sx-deployer:
    image: ubuntu:focal
    container_name: sx-deployer
    environment:
      - TZ=America/Denver
    volumes:
      #- ./entrypoint.sh:/workspaces/entrypoint.sh
      #- ./.env.gpg:/workspaces/.env.gpg
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    tty: true
    stdin_open: true
    #command: ["/workspaces/entrypoint.sh"]
    logging:
        options:
            max-size: 1g
    restart: unless-stopped
